server {
    listen 443 ssl;
    http2 on;

    server_name 139.190.96.203;

    ssl_certificate /etc/letsencrypt/live/139.190.96.203/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/139.190.96.203/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location /cashmate/ {
        proxy_pass http://cashmate_api/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        proxy_read_timeout 60s;
    }
}
